# Reshaping, Concatenating and Splitting Arrays 

In [1]:
# import numpy 
import numpy as np

---

# A. Reshaping Arrays 

In [2]:
# Let us convert a 1 D array by reshaping it to a 2 D array 
array_1D = np.linspace(start=2, stop=20, num=9)
print(f"Original 1 D array: \n{array_1D}")

array_1D_reshape_2D = array_1D.reshape((3,3))
print(f"The 1 D array after being reshaped to a 2 D array:\n{array_1D_reshape_2D}")

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
The 1 D array after being reshaped to a 2 D array:
[[ 2.    4.25  6.5 ]
 [ 8.75 11.   13.25]
 [15.5  17.75 20.  ]]


In [3]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D.reshape((1,9))
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D.reshape((9,1))
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


There is an alternate way to acieve the same result! Here we will use the `np.newaxis`

## `np.newaxis()`

In [4]:
# Often we convert 1 D array into a 2 D row or a column matrix
print(f"Original 1 D array: \n{array_1D}")

# reshaping the 1 D to a row vector 
array_1D_rowvec = array_1D[np.newaxis,:]
print('Row Vector:')
print(array_1D_rowvec)

# reshaping the 1 D to a column vector 
array_1D_colvec = array_1D[:, np.newaxis]
print('Column Vector:')
print(array_1D_colvec)

Original 1 D array: 
[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]
Row Vector:
[[ 2.    4.25  6.5   8.75 11.   13.25 15.5  17.75 20.  ]]
Column Vector:
[[ 2.  ]
 [ 4.25]
 [ 6.5 ]
 [ 8.75]
 [11.  ]
 [13.25]
 [15.5 ]
 [17.75]
 [20.  ]]


---

# B. Concatenating two arrays

## 🧠 Thumb Rule for axis in NumPy
- `axis=0` (Vertical): Rows add up — columns must match
- `axis=1` (Horizontal): Columns add up — rows must match

In [ ]:
# concatenating three 1 D arrays 
array_1 = np.array([1,2,3]) 
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

array_concat = np.concatenate([array_1, array_2, array_3]) # note pass the three arrays in a list
print(array_concat) # concatenates to a 1D array

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Vertical concatenate 
a = np.array([[1, 2],
              [3, 4]]) # (2,2)

b = np.array([[5, 6]]) # (1,2) i.e the column dim do match i.e. it has to be a row vector with the same dimension

result = np.concatenate((a, b), axis=0) # note the axis 
result

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# horixontal concatenate 
a = np.array([[1, 2],
              [3, 4]]) # (2,2)

b = np.array([[5],
              [6]]) # (2,1) - the row dim matches i.e it has to be a column vector of the same dimension 

result = np.concatenate((a, b), axis=1)
result

array([[1, 2, 5],
       [3, 4, 6]])

So far, we have concatenated the arrays having the same dimensions. However, in reality, it is often the case where the dimensions are not equal. In such cases of **MIXED DIMENSIONS**, one should preferably use `np.hstack` and `np.vstack`

## `np.hstack()` & `np.vstack()`

First, I will use `concatenate()` to achieve the result and this will help you understand where the two functions help us.

In [ ]:
# consider a array 
print(array_1)
print(array_1.shape) # the shape is (3,)

[1 2 3]
(3,)


In [9]:
# consider another array 
array_4 = array_concat.reshape((3,3))
print(array_4)
print(array_4.shape) # (3,3) is the shape 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


So, `array_1` and `array_4` have mixed dimensions. One of the array is a 1D array while the other is a 2D array. 

In [10]:
# vertically stack the array 
np.concatenate([array_1[np.newaxis,:], array_4])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# horizontally stack 
np.concatenate([array_1[:, np.newaxis], array_4], axis=1)

array([[1, 1, 2, 3],
       [2, 4, 5, 6],
       [3, 7, 8, 9]])

Now, let us do the achieve the same result using `np.hstack()` and `np.vstack()`. Here, you don't need to mention the `axis` parameter like the `np.concatenate()`! 

In [13]:
# np.hstack and np.vstack
# say, I want to concatenate array_1 to array_4 row-wise i.e. vertically stack the arrays
print('Vertical Stack')
print(np.vstack([array_1, array_4]))

# better reshape the 1D vector to a 2D - makes more sense !
print('Vertical Stack after reshaping')
print(np.vstack([array_4,array_1[np.newaxis,:]])) # order matters

# Let us now stack horizontally 
# before we stack it horizontally, we need to make it a column vector
print('Horizontal Stack ( Always Reshape to match the row dim)') 
array_5 = array_1[:, np.newaxis]
print(np.hstack([array_5, array_4]))

Vertical Stack
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
Vertical Stack after reshaping
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
Horizontal Stack ( Always Reshape to match the row dim)
[[1 1 2 3]
 [2 4 5 6]
 [3 7 8 9]]


---

# C.  Splitting Arrays 

In [14]:
# split the array_concat into three different arrays
print(f"The concatenated array: {array_concat}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=[3,6])
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

arr_split_1, arr_split_2, arr_split_3 = np.split(array_concat, indices_or_sections=3)
print(f"The three splits are: {arr_split_1}, {arr_split_2}, {arr_split_3}")

The concatenated array: [1 2 3 4 5 6 7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]
The three splits are: [1 2 3], [4 5 6], [7 8 9]


Now, let us split a 2D array!

In [15]:
# construct a 2D array using vstack
array_concat_row = np.vstack([array_4, array_4])
array_concat_row

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Vertical Split using `np.split()`

In [16]:
# vertical split using np.split()
np.split(array_concat_row, indices_or_sections=2, axis=0)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

### Vertical Split using `np.vsplit()`

In [17]:
# alternate way to split vertically 
np.vsplit(ary=array_concat_row, indices_or_sections=2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [18]:
# split at a particular index 
np.vsplit(ary=array_concat_row, indices_or_sections=[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

### Horizontal Split using `np.hsplit()`
- Note that, I can also use the `np.split()` function to do a horizontal split - in that case the `axis` should be set to 1

In [19]:
# let us do a horizontal split now 
np.hsplit(ary=array_concat_row, indices_or_sections=[2]) # hsplits at index 2 

[array([[1, 2],
        [4, 5],
        [7, 8],
        [1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9],
        [3],
        [6],
        [9]])]

In [20]:
# alternate way
np.split(array_concat_row, indices_or_sections=[2], axis=1)

[array([[1, 2],
        [4, 5],
        [7, 8],
        [1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9],
        [3],
        [6],
        [9]])]

---