# Indexing And Slicing an Array 

In [12]:
# import numpy 
import numpy as np

---

# A. Attributes of NumPy Array
- `ndim` - gives the dimensions of each array
- `shape` - gives the shape of each array as a tuple 
- `size` - gives the total number of elements in the array
- `dtype` - gives the data type of the array

In [13]:
# contruct an array
array_int_1D = np.random.randint(low=2, high=20, size=6) # 1 dimensional
array_int_2D = np.random.randint(low=2, high=20, size=(4,5)) # 2 dimensional
array_int_3D = np.random.randint(low=2, high=20, size=(3,4,5)) # 3 dimensional

# accessing the attributes of the array

# gives the dimensions of the three arrays
print(f"The dimensions are : {array_int_1D.ndim}, {array_int_2D.ndim}, {array_int_3D.ndim}") 

# gives the shape of the arrays 
print(f"The shape are : {array_int_1D.shape}, {array_int_2D.shape}, {array_int_3D.shape}") 

# gives the total number of elements in the array
print(f"The sizes are : {array_int_1D.size}, {array_int_2D.size}, {array_int_3D.size}")

# gives the datatype of the elements of the array
print(f"The datatypes are : {array_int_1D.dtype}, {array_int_2D.dtype}, {array_int_3D.dtype}") 

The dimensions are : 1, 2, 3
The shape are : (6,), (4, 5), (3, 4, 5)
The sizes are : 6, 20, 60
The datatypes are : int32, int32, int32


---

# B. Array Indexing 

Let us first have a look at the three ARRAYS we just created!

In [14]:
print("ARRAY 1")
print(array_int_1D,'\n')

print("ARRAY 2")
print(array_int_2D,'\n')

print("ARRAY 3")
print(array_int_3D)

ARRAY 1
[16  7  9 10  3 16] 

ARRAY 2
[[ 4 19 15 15  2]
 [12  4 16 13 18]
 [14 15 18 13 14]
 [ 3  5 16 17  7]] 

ARRAY 3
[[[18  9  2  4  3]
  [ 4  9 10 19  3]
  [15  9 14 17  7]
  [16 16 18  3  6]]

 [[14 18 16  7 11]
  [ 4 14 17 18  5]
  [11 17 11 12 10]
  [10 14  7 15 11]]

 [[11 17  9  2 11]
  [ 2 16 15  6 18]
  [18 17  2 18 18]
  [16 16 16  4 19]]]


In [15]:
# indexing arrays

# find the second element of the ARRAY 1
print(f'The second element of the 1 D array stated above is : {array_int_1D[1]}')

# find the element present at position (1,2) of the ARRAY 2 (note that indexing starts at 0)
print(f'The (1,2)th element i.e. the element at the intersection of the second row and the 3rd column is : {array_int_2D[1,2]}')

# find the element at position (1,2,0)
print(f'The element at (1,2,0)th position is : {array_int_3D[1,2,0]}')

The second element of the 1 D array stated above is : 7
The (1,2)th element i.e. the element at the intersection of the second row and the 3rd column is : 16
The element at (1,2,0)th position is : 11


---

# C. Array Slicing 

For better visualization of the results, let me print the three arrays once more! 

In [16]:
print("ARRAY 1")
print(array_int_1D,'\n')

print("ARRAY 2")
print(array_int_2D,'\n')

print("ARRAY 3")
print(array_int_3D)

ARRAY 1
[16  7  9 10  3 16] 

ARRAY 2
[[ 4 19 15 15  2]
 [12  4 16 13 18]
 [14 15 18 13 14]
 [ 3  5 16 17  7]] 

ARRAY 3
[[[18  9  2  4  3]
  [ 4  9 10 19  3]
  [15  9 14 17  7]
  [16 16 18  3  6]]

 [[14 18 16  7 11]
  [ 4 14 17 18  5]
  [11 17 11 12 10]
  [10 14  7 15 11]]

 [[11 17  9  2 11]
  [ 2 16 15  6 18]
  [18 17  2 18 18]
  [16 16 16  4 19]]]


In [17]:
# Slicing a 1 D array
print(f"Sliced 1D array : {array_int_1D[3:]}")
print(f"Every second element of the 1D array: {array_int_1D[::2]}")
print(f"every second element from index 3, reversed : {array_int_1D[3::-2]}")

# Slicing a 2 D array - Multidimensional Subarrays 
print(f"First 2 rows and 3 columns:\n{array_int_2D[:2, :3]}")
print(f"All rows and every second column:\n {array_int_2D[:, ::2]}")
print(f"Rows ordering reversed(i.e. last row becomes the first row and so on):\n{array_int_2D[::-1,:]}")
print(f"Columns ordering reversed: \n{array_int_2D[:,::-1]}")
print(f"Both row and column ordering reversed:\n{array_int_2D[::-1,::-1]}")

# Common operations on a 2D array - involves both indexing and slicing 
# The result is a 1D array 
print(f"Second column:\n{array_int_2D[:, 1]}")
print(f"Second row:\n{array_int_2D[1,:]}")

Sliced 1D array : [10  3 16]
Every second element of the 1D array: [16  9  3]
every second element from index 3, reversed : [10  7]
First 2 rows and 3 columns:
[[ 4 19 15]
 [12  4 16]]
All rows and every second column:
 [[ 4 15  2]
 [12 16 18]
 [14 18 14]
 [ 3 16  7]]
Rows ordering reversed(i.e. last row becomes the first row and so on):
[[ 3  5 16 17  7]
 [14 15 18 13 14]
 [12  4 16 13 18]
 [ 4 19 15 15  2]]
Columns ordering reversed: 
[[ 2 15 15 19  4]
 [18 13 16  4 12]
 [14 13 18 15 14]
 [ 7 17 16  5  3]]
Both row and column ordering reversed:
[[ 7 17 16  5  3]
 [14 13 18 15 14]
 [18 13 16  4 12]
 [ 2 15 15 19  4]]
Second column:
[19  4 15  5]
Second row:
[12  4 16 13 18]


**NOTE**

Unlike the Python list slices, NumPy array slices are returned as ***VIEWS*** rather than ***COPIES*** of the array data. Thus, any change made to the view, also impacts the original data.

In [18]:
# Illustration of the above point 
# Consider the 2 D array we are dealing with 
print(array_int_2D)

[[ 4 19 15 15  2]
 [12  4 16 13 18]
 [14 15 18 13 14]
 [ 3  5 16 17  7]]


In [19]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Original array has changed too!:\n{array_int_2D}")

Sliced Subarray:
[[ 4 19]
 [12  4]]
Sliced Subarray after modification:
[[100  19]
 [ 12   4]]
Original array has changed too!:
[[100  19  15  15   2]
 [ 12   4  16  13  18]
 [ 14  15  18  13  14]
 [  3   5  16  17   7]]


---

# D. Fancy Indexing/Slicing

**✨ What is Fancy Slicing in NumPy?**

- In NumPy, Fancy Slicing (or Fancy Indexing) means accessing elements using arrays (or lists) of indices, instead of using just a range or slice.

- It gives you more flexibility — like picking out specific elements, rows, or columns in any order you want.

In [20]:
# let us slice this 2 D array and make another subarray usinf Fancy Indexing 
subarray_int_2D = array_int_2D[[1,3], :]
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the (0,1) element of the subarray to 100
subarray_int_2D[0,1] = 100
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"The array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[12  4 16 13 18]
 [ 3  5 16 17  7]]
Sliced Subarray after modification:
[[ 12 100  16  13  18]
 [  3   5  16  17   7]]
The array has not changed:
[[100  19  15  15   2]
 [ 12   4  16  13  18]
 [ 14  15  18  13  14]
 [  3   5  16  17   7]]


**Key Difference**
- Simple slicing (like `array_int_2D[:2, :2]`) produces a **view**.
- Fancy indexing (like `array_int_2D[[1, 3], :]`) produces a **copy**.

### Using `copy()` method
- We can, however, use the `copy()` method to deliberately create a copy in case of slicing

In [21]:
# let us slice this 2 D array and make another subarray
subarray_int_2D = array_int_2D[:2, :2].copy()
print(f"Sliced Subarray:\n{subarray_int_2D}")

# let us change the first element of the subarray to 100
subarray_int_2D[0,0] = 200
print(f"Sliced Subarray after modification:\n{subarray_int_2D}")

# Let us see the original array now!
print(f"Array has not changed:\n{array_int_2D}")

Sliced Subarray:
[[100  19]
 [ 12   4]]
Sliced Subarray after modification:
[[200  19]
 [ 12   4]]
Array has not changed:
[[100  19  15  15   2]
 [ 12   4  16  13  18]
 [ 14  15  18  13  14]
 [  3   5  16  17   7]]


---